# Puerto donde correrá este microservicio
server.port=8001

# Nombre del microservicio (para Eureka)
spring.application.name=msvc-peliculas

# Configuración de Base de Datos Local MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/cine_peliculas_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
# contraseña de MySQL
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate: Crea las tablas automáticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# URL del servidor Eureka para registrarse
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

eureka.instance.prefer-ip-address=true
